USE [master]
GO
/****** Object:  Database [20212C_TP]    Script Date: 10/13/2021 11:34:49 PM ******/
CREATE DATABASE [20212C_TP]
GO
ALTER DATABASE [20212C_TP] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [20212C_TP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [20212C_TP] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [20212C_TP] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [20212C_TP] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [20212C_TP] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [20212C_TP] SET ARITHABORT OFF 
GO
ALTER DATABASE [20212C_TP] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [20212C_TP] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [20212C_TP] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [20212C_TP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [20212C_TP] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [20212C_TP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [20212C_TP] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [20212C_TP] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [20212C_TP] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [20212C_TP] SET  DISABLE_BROKER 
GO
ALTER DATABASE [20212C_TP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [20212C_TP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [20212C_TP] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [20212C_TP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [20212C_TP] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [20212C_TP] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [20212C_TP] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [20212C_TP] SET RECOVERY FULL 
GO
ALTER DATABASE [20212C_TP] SET  MULTI_USER 
GO
ALTER DATABASE [20212C_TP] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [20212C_TP] SET DB_CHAINING OFF 
GO
ALTER DATABASE [20212C_TP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [20212C_TP] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [20212C_TP] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [20212C_TP] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'20212C_TP', N'ON'
GO
ALTER DATABASE [20212C_TP] SET QUERY_STORE = OFF
GO
USE [20212C_TP]
GO
/****** Object:  Table [dbo].[Ratings]    Script Date: 10/13/2021 11:34:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ratings](
	[RatingId] [int] IDENTITY(1,1) NOT NULL,
	[EventId] [int] NOT NULL,
	[DinerId] [int] NOT NULL,
	[Rating] [int] NOT NULL,
	[Comments] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Ratings] PRIMARY KEY CLUSTERED 
(
	[RatingId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Events]    Script Date: 10/13/2021 11:34:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Events](
	[EventId] [int] IDENTITY(1,1) NOT NULL,
	[ChefId] [int] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Description] [nvarchar](200) NOT NULL,
	[Date] [datetime] NOT NULL,
	[DinersAmount] [int] NOT NULL,
	[Location] [nvarchar](50) NOT NULL,
	[Picture] [nvarchar](50) NOT NULL,
	[Price] [decimal](18, 2) NOT NULL,
	[State] [int] NOT NULL,
	[CreatedDate] [datetime],
	[CreatedBy] [nvarchar](50),
	[ModifiedDate] [datetime],
	[ModifiedBy] [nvarchar](50),
	[DeletedDate] [datetime],
	[DeletedBy] [nvarchar](50),

 CONSTRAINT [PK_Events] PRIMARY KEY CLUSTERED 
(
	[EventId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EventsRecipes]    Script Date: 10/13/2021 11:34:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EventsRecipes](
	[EventRecipeId] [int] IDENTITY(1,1) NOT NULL,
	[EventId] [int] NOT NULL,
	[RecipeId] [int] NOT NULL,
 CONSTRAINT [PK_EventsRecipes] PRIMARY KEY CLUSTERED 
(
	[EventRecipeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Recipes]    Script Date: 10/13/2021 11:34:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Recipes](
	[RecipeId] [int] IDENTITY(1,1) NOT NULL,
	[ChefId] [int] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[CookingTime] [int] NOT NULL,
	[Description] [nvarchar](max) NOT NULL,
	[Ingredients] [nvarchar](max) NOT NULL,
	[RecipeTypeId] [int] NOT NULL,
	[CreatedDate] [datetime],
	[CreatedBy] [nvarchar](50),
	[ModifiedDate] [datetime],
	[ModifiedBy] [nvarchar](50),
	[DeletedDate] [datetime],
	[DeletedBy] [nvarchar](50),
 CONSTRAINT [PK_Recipes] PRIMARY KEY CLUSTERED 
(
	[RecipeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Bookings]    Script Date: 10/13/2021 11:34:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Bookings](
	[BookId] [int] IDENTITY(1,1) NOT NULL,
	[EventId] [int] NOT NULL,
	[DinerId] [int] NOT NULL,
	[RecipeId] [int] NOT NULL,
	[DinersAmount] [int] NOT NULL,
	[CreationDate] [datetime] NOT NULL,
 CONSTRAINT [PK_Bookings] PRIMARY KEY CLUSTERED 
(
	[BookId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RecipesType]    Script Date: 10/13/2021 11:34:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RecipesType](
	[RecipeTypeId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_RecipeType] PRIMARY KEY CLUSTERED 
(
	[RecipeTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 10/13/2021 11:34:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](30) NOT NULL,
	[Rol] [int] NOT NULL,
	[RegistrationDate] [datetime] NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Ratings]  WITH CHECK ADD  CONSTRAINT [FK_Ratings_Events] FOREIGN KEY([EventId])
REFERENCES [dbo].[Events] ([EventId])
GO
ALTER TABLE [dbo].[Ratings] CHECK CONSTRAINT [FK_Ratings_Events]
GO
ALTER TABLE [dbo].[Ratings]  WITH CHECK ADD  CONSTRAINT [FK_Ratings_Users] FOREIGN KEY([DinerId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[Ratings] CHECK CONSTRAINT [FK_Ratings_Users]
GO
ALTER TABLE [dbo].[Events]  WITH CHECK ADD  CONSTRAINT [FK_Events_Users] FOREIGN KEY([ChefId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[Events] CHECK CONSTRAINT [FK_Events_Users]
GO
ALTER TABLE [dbo].[EventsRecipes]  WITH CHECK ADD  CONSTRAINT [FK_EventsRecipes_Events] FOREIGN KEY([EventId])
REFERENCES [dbo].[Events] ([EventId])
GO
ALTER TABLE [dbo].[EventsRecipes] CHECK CONSTRAINT [FK_EventsRecipes_Events]
GO
ALTER TABLE [dbo].[EventsRecipes]  WITH CHECK ADD  CONSTRAINT [FK_EventsRecipes_Recipes] FOREIGN KEY([RecipeId])
REFERENCES [dbo].[Recipes] ([RecipeId])
GO
ALTER TABLE [dbo].[EventsRecipes] CHECK CONSTRAINT [FK_EventsRecipes_Recipes]
GO
ALTER TABLE [dbo].[Recipes]  WITH CHECK ADD  CONSTRAINT [FK_Recipes_RecipesType] FOREIGN KEY([RecipeTypeId])
REFERENCES [dbo].[RecipesType] ([RecipeTypeId])
GO
ALTER TABLE [dbo].[Recipes] CHECK CONSTRAINT [FK_Recipes_RecipesType]
GO
ALTER TABLE [dbo].[Bookings]  WITH CHECK ADD  CONSTRAINT [FK_Bookings_Events] FOREIGN KEY([EventId])
REFERENCES [dbo].[Events] ([EventId])
GO
ALTER TABLE [dbo].[Bookings] CHECK CONSTRAINT [FK_Bookings_Events]
GO
ALTER TABLE [dbo].[Bookings]  WITH CHECK ADD  CONSTRAINT [FK_Bookings_Recipes] FOREIGN KEY([RecipeId])
REFERENCES [dbo].[Recipes] ([RecipeId])
GO
ALTER TABLE [dbo].[Bookings] CHECK CONSTRAINT [FK_Bookings_Recipes]
GO
ALTER TABLE [dbo].[Bookings]  WITH CHECK ADD  CONSTRAINT [FK_Bookings_Users] FOREIGN KEY([DinerId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[Bookings] CHECK CONSTRAINT [FK_Bookings_Users]
GO
USE [master]
GO
ALTER DATABASE [20212C_TP] SET  READ_WRITE 
GO
